#!/bin/bash
#
# Concatenates the Lox sources listed in a MANIFEST.* file into a single
# script, plus a .map file for translating bundle line numbers back to sources.
#
#   ./bundle.sh                         bundle every known MANIFEST.*, then
#                                       copy build/loxi.lox to Lox.lox
#   ./bundle.sh MANIFEST.x build/out    write build/out.lox, build/out.map and
#                                       the runner script build/bin/out
#   ./bundle.sh where build/out.map N   print the source file:line of bundle line N
#
# A manifest lists one path per line, relative to the repository root; blank
# lines and lines starting with '#' are ignored. A line "include MANIFEST.y"
# lists MANIFEST.y's sources at that point. The .map file has one line per
# source: "<first bundle line> <path>".

set -euo pipefail

cd "$(dirname "$0")"

fail() {
    echo "bundle: $*" >&2
    exit 1
}

# expand MANIFEST [INCLUDING...]: appends MANIFEST's sources to SOURCES,
# expanding includes; INCLUDING is the chain of manifests including it.
SOURCES=()
expand() {
    local manifest="$1"
    shift
    [ -f "$manifest" ] || fail "no such manifest: $manifest${1:+ (included by $1)}"
    local m
    for m in "$@"; do
        [ "$m" = "$manifest" ] || continue
        fail "include cycle: $manifest"
    done

    local entry
    while IFS= read -r entry || [ -n "$entry" ]; do
        case "$entry" in
            ''|'#'*) ;;
            'include '*) expand "${entry#include }" "$manifest" "$@" ;;
            *)
                [ -f "$entry" ] || fail "no such file: $entry (in $manifest)"
                SOURCES+=("$entry")
                ;;
        esac
    done < "$manifest"
}

# replace TMP DEST: moves TMP to DEST unless DEST already has the same
# contents, so DEST's timestamp only changes when it does (the jar runner
# compares it against the jar's).
replace() {
    if cmp -s "$1" "$2"; then
        rm -f "$1"
    else
        mv "$1" "$2"
    fi
}

# runner MANIFEST OUT: writes the script DIR/bin/NAME (for OUT = DIR/NAME),
# which runs OUT.lox on a host Lox interpreter.
runner() {
    local manifest="$1" out="$2"
    local dir name
    dir=$(cd "$(dirname "$out")" && pwd)
    name=$(basename "$out")
    mkdir -p "$dir/bin"

    {
        cat <<HEADER
#!/usr/bin/env bash
# Generated by bundle.sh from $manifest: do not edit, rerun ./bundle.sh.
#
# Runs $name.lox on the Lox script \$1 (or stdin), using the host interpreter
# chosen by LOX_HOST:
#   clox   clox/clox (default)
#   jlox   the patched craftinginterpreters jlox interpreter
#   jloxc  the jlox compiler
#   jar    $name.jar, compiled from $name.lox by the jlox compiler in ./build.sh
# Stack trace lines from a crash inside $name.lox, "[line N] in f()" as printed
# by clox, are rewritten to the source file and line using $name.map.

root=$(printf %q "$PWD")
bundle=$(printf %q "$dir/$name.lox")
map=$(printf %q "$dir/$name.map")
jar=$(printf %q "$dir/$name.jar")
HEADER
        cat <<'BODY'
java="${JAVA_HOME:+$JAVA_HOME/bin/}java"

case "${LOX_HOST:-clox}" in
    clox)  host=("$root/clox/clox" "$bundle") ;;
    jlox)  host=("$java" -cp "$root/jlox/craftinginterpreters/build/java" com.craftinginterpreters.lox.Lox "$bundle") ;;
    jloxc) host=("$root/jlox/bin/jlox" "$bundle") ;;
    jar)
        [ -f "$jar" ] || { echo "$jar not found: run ./build.sh" >&2; exit 69; }
        [ "$jar" -ot "$bundle" ] && echo "warning: $jar is older than $bundle: run ./build.sh" >&2
        host=("$java" -jar "$jar")
        ;;
    *)
        echo "unknown LOX_HOST: $LOX_HOST (expected clox, jlox, jloxc or jar)" >&2
        exit 64
        ;;
esac

if [ $# -gt 0 ]; then
    exec < "$1" || exit 66
fi

"${host[@]}" 2> >(awk -v map="$map" '
    BEGIN {
        while ((getline entry < map) > 0) {
            split(entry, f, " ")
            n++
            first[n] = f[1]
            path[n] = f[2]
        }
    }
    /^\[line [0-9]+\] in / {
        line = substr($0, 7) + 0
        for (i = n; i > 0 && first[i] > line; i--) ;
        if (i > 0) $0 = "[" path[i] ":" (line - first[i] + 1) "]" substr($0, index($0, "]") + 1)
    }
    { print; fflush() }' >&2)
status=$?
wait $!
exit $status
BODY
    } > "$dir/bin/$name.tmp"
    chmod +x "$dir/bin/$name.tmp"
    replace "$dir/bin/$name.tmp" "$dir/bin/$name"
}

# bundle MANIFEST OUT: writes OUT.lox, OUT.map and the runner script.
bundle() {
    local manifest="$1" out="$2"
    SOURCES=()
    expand "$manifest"
    mkdir -p "$(dirname "$out")"

    local lox="$out.lox.tmp" map="$out.map.tmp"
    trap "rm -f '$lox' '$map'" EXIT
    : > "$lox"
    : > "$map"

    local line=1 path
    for path in "${SOURCES[@]}"; do
        [ -s "$path" ] && [ "$(tail -c1 "$path")" = "" ] || fail "missing final newline: $path"
        echo "$line $path" >> "$map"
        cat "$path" >> "$lox"
        line=$((line + $(wc -l < "$path")))
    done

    local dups
    dups=$(grep -oE '^(var|fun|class) [A-Za-z_][A-Za-z0-9_]*' "$lox" | awk '{print $2}' | sort | uniq -d)
    if [ -n "$dups" ]; then
        local name
        for name in $dups; do
            echo "bundle: duplicate top-level name: $name" >&2
            grep -nE "^(var|fun|class) $name\b" "$lox" | while IFS=: read -r n _; do
                echo "  $(where "$map" "$n")" >&2
            done
        done
        exit 1
    fi

    if [ "$(basename "$manifest")" = "MANIFEST.runtime" ]; then
        : # TODO: runtime-mode check (Step 23).
    fi

    replace "$lox" "$out.lox"
    replace "$map" "$out.map"
    runner "$manifest" "$out"
    echo "bundled $manifest -> $out.lox ($((line - 1)) lines), runner $(dirname "$out")/bin/$(basename "$out")"
}

# where MAP LINE: maps a bundle line to "path:line" using the last map entry
# whose first line is <= LINE.
where() {
    awk -v n="$2" '$1 <= n { first = $1; path = $2 }
        END {
            if (path == "") exit 1
            print path ":" (n - first + 1)
        }' "$1" || fail "line $2 is not in $1"
}

# Manifests built when run without arguments, with their output names.
ALL="MANIFEST.interpreter:build/loxi MANIFEST.compiler:build/loxc MANIFEST.astprinter:build/loxast"

case "${1:-}" in
    "")
        for entry in $ALL; do
            manifest="${entry%%:*}"
            [ -f "$manifest" ] && bundle "$manifest" "${entry#*:}"
        done
        cmp -s build/loxi.lox Lox.lox || cp build/loxi.lox Lox.lox
        echo "copied build/loxi.lox -> Lox.lox"
        ;;
    where)
        [ $# -eq 3 ] || fail "usage: $0 where MAP LINE"
        where "$2" "$3"
        ;;
    *)
        [ $# -eq 2 ] || fail "usage: $0 [MANIFEST OUT | where MAP LINE]"
        bundle "$1" "$2"
        ;;
esac
